services:
  talemate:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CUDA_AVAILABLE=${CUDA_AVAILABLE:-false}
    expose:
      - "6800"
      - "5050"
    volumes:
      - /data/talemate/config.yaml:/app/config.yaml
      - /data/talemate/scenes:/app/scenes
      - /data/talemate/templates:/app/templates
      - /data/talemate/chroma:/app/chroma
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/src:$PYTHONPATH
    command: ["/bin/bash", "-c", "source /app/talemate_env/bin/activate && python src/talemate/server/run.py runserver --host 0.0.0.0 --port 5050 --frontend-host 0.0.0.0 --frontend-port 8080"]
